SELECT VERSION() AS `version`;
SELECT * FROM `COLUMNS` WHERE `TABLE_SCHEMA` = 'konfio_customer' AND `TABLE_NAME` = 'migrations';
SELECT * FROM `migrations` `migrations` ORDER BY `id` DESC;
START TRANSACTION;
CREATE TABLE `parties` (`id` varchar(36) NOT NULL, `name` varchar(255) NOT NULL, `email` varchar(255) NOT NULL, `role` enum ('ADMIN', 'EMPLOYEE', 'READ_ONLY') NOT NULL DEFAULT 'READ_ONLY', `customerId` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
CREATE TABLE `contact_info` (`id` varchar(36) NOT NULL, `email` varchar(255) NOT NULL, `phone` varchar(255) NULL, `address` varchar(255) NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;
CREATE TABLE `customers` (`id` varchar(36) NOT NULL, `name` varchar(255) NOT NULL, `email` varchar(255) NOT NULL, `taxId` varchar(255) NOT NULL, `type` enum ('ENTERPRISE', 'INDIVIDUAL') NOT NULL DEFAULT 'INDIVIDUAL', PRIMARY KEY (`id`)) ENGINE=InnoDB;
ALTER TABLE `parties` ADD CONSTRAINT `FK_4802403ec96bcde9f00e7bbd7e0` FOREIGN KEY (`customerId`) REFERENCES `customers`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
INSERT INTO `migrations`(`timestamp`, `name`) VALUES (?, ?) -- PARAMETERS: [1743733487514,"V11743733487514"];
COMMIT;