services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: konfio-customer-api
    restart: always
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: 123456
      DB_DATABASE: konfio_customer
      DB_MIGRATE: true
      DB_MIGRATIONS_TABLE_NAME: migrations
      DB_LOG: false
      KAFKA_BROKERS: kafka:9092
      KAFKA_CLIENT_ID: konfio-customer-api
      KAFKA_GROUP_ID: konfio-customer-group
      LOG_LEVEL: info
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_TTL: 3600
      REDIS_MAX_ITEMS: 100
    networks:
      - konfio_network

networks:
  konfio_network:
    external: true
